<?php

namespace app\models;

use app\models\behaviors\ChangelogBehavior;
use app\models\common\GeneralLifespanExperimentQuery;
use app\models\common\LifespanExperimentQuery;
use app\models\common\LifespanExperimentToOrtholog;
use app\models\exceptions\UpdateExperimentsException;
use app\models\traits\ExperimentsActiveRecordTrait;
use app\models\traits\ValidatorsTrait;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "age".
 *
 */
class LifespanExperiment extends common\LifespanExperiment
{
    use ValidatorsTrait;
    use ExperimentsActiveRecordTrait;

    public const TYPE_ORTHOLOG = 1;
    public const TYPE_TISSUE = 2;
    public $delete = false;
    public $tissuesIds;
    private $tissuesIdsArray;
    private $orthologIds = [];
    private $modelOrganismId;

    public function behaviors()
    {
        return [
            ChangelogBehavior::class
        ];
    }

    public static function createByParams($params = [])
    {
        $ar = new self();
        foreach ($params as $name => $value) {
            $ar->$name = $value;
        }
        if (!$ar->general_lifespan_experiment_id) {
            $generalLifespanExperiment = new GeneralLifespanExperiment();
            $generalLifespanExperiment->save();
            $generalLifespanExperiment->refresh();
            $ar->general_lifespan_experiment_id = $generalLifespanExperiment->id;
            $ar->link('generalLifespanExperiment', $generalLifespanExperiment);
            $ar->populateRelation('generalLifespanExperiment', $generalLifespanExperiment);
            $ar->save();
        }
        return $ar;
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return ArrayHelper::merge(
            parent::rules(), [
            [['gene_id', 'gene_intervention_method_id'], 'safe'], // todo OG-410
            [['tissuesIds', 'intervention_result_id', 'orthologIds'], 'safe'],
            [['age'], 'number', 'min' => 0],
            [['reference'], 'validateDOI']
        ]);
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(
            parent::attributeLabels(), [
            'delete' => 'Удалить',
            'gene_intervention_id' => 'Вмешательство',
            'intervention_result_id' => 'Результат вмешательства',
            'model_organism_id' => 'Объект',
            'tissue_specificity' => 'Тканеспецифичность',
            'mutation_induction' => 'Индукция мутации отменой препарата',
            'tissue_specific_promoter' => 'Тканеспецифичный промотер',
            'age' => 'Возраст',
            'reference' => 'Ссылка',
            'age_unit' => 'Ед. измерения возраста',
        ]);
    }

    /**
     * {@inheritdoc}
     * @return LifespanExperimentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new LifespanExperimentQuery(get_called_class());
    }

    /**
     * @return bool
     * @throws \yii\base\InvalidConfigException
     */
    public function beforeValidate()
    {
        foreach ($this->getTableSchema()->columns as $column) {
            if ($column->type == 'float') {
                $attr = $column->name;
                $this->$attr = trim(str_replace(',', '.', $this->$attr));
            }
        }
        $this->age = str_replace(',', '.', $this->age);
        $this->reference = trim($this->reference);

        return parent::beforeValidate();
    }
    public function afterSave($insert, $changedAttributes)
    {
        if (Yii::$app instanceof \yii\console\Application) { // todo продумать нормальный фикс
            return parent::afterSave($insert, $changedAttributes);
        }

        parent::afterSave($insert, $changedAttributes);
    }

    /**
     * Gets query for [[GeneralLifespanExperiment]].
     *
     * @return \yii\db\ActiveQuery|GeneralLifespanExperimentQuery
     */
    public function getGeneralLifespanExperiment()
    {
        return $this->hasOne(GeneralLifespanExperiment::class, ['id' => 'general_lifespan_experiment_id']);
    }

    public static function findAllAsArray()
    {
        $result = [];
        $ages = self::find()->all();
        foreach ($ages as $age) {
            $result[$age->id] = $age->name_phylo;
        }

        return $result;
    }
    
    public function beforeDelete()
    {
        $tissues = LifespanExperimentToTissue::find()->where(
            ['lifespan_experiment_id' => $this->id]
        )->all();
        foreach ($tissues as $arToDelete) { // one by one for properly triggering "afterDelete" event
            $arToDelete->delete();
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $modelArrays
     * @param int $geneId
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public static function saveMultipleForGene(array $modelArrays)
    {
        foreach ($modelArrays as $id => $modelArray) {
            if (is_numeric($id)) {
                $modelAR = self::findOne($id);
                if (!$modelAR) {
                    continue;
                }
            } else {
                $modelAR = new self();
            }
            if ($modelArray['delete'] === '1' && $modelAR instanceof ActiveRecord) {
                $modelAR->delete();
                continue;
            }
            $modelAR->setAttributes($modelArray);
            self::setAttributeFromNewAR($modelArray, 'gene_intervention_method_id', 'GeneInterventionMethod', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'active_substance_id', 'ActiveSubstance', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'active_substance_delivery_way_id', 'ActiveSubstanceDeliveryWay', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'treatment_period_id', 'TreatmentPeriod', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'treatment_period_id', 'TreatmentPeriod', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'treatment_start_time_unit_id', 'TreatmentTimeUnit', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'treatment_end_time_unit_id', 'TreatmentTimeUnit', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'treatment_start_stage_of_development_id', 'TreatmentStageOfDevelopment', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'treatment_end_stage_of_development_id', 'TreatmentStageOfDevelopment', $modelAR);
            self::setAttributeFromNewAR($modelArray, 'genotype', 'Genotype', $modelAR);

//            Ortholog::createNewByIds($modelArray['orthologIds'], $modelAR->general_lifespan_experiment_id, $modelAR->gene_id);

            if ($modelAR->organism_line_id === '') {
                $modelAR->organism_line_id = null;
            }
            if ($modelAR->genotype === '') {
                $modelAR->genotype = null;
            }
            if (!$modelAR->validate() || !$modelAR->save()) {
                throw new UpdateExperimentsException($id, $modelAR);
            }
            $modelAR->saveForeignEntity(self::TYPE_TISSUE, $modelArray['tissuesIdsArray']);
//            $modelAR->saveTissues($modelArray['tissuesIdsArray']);
//            $modelAR->saveOrthologs($modelArray['orthologIds']);
            $modelAR->saveForeignEntity(self::TYPE_ORTHOLOG,
                                                    $modelArray['orthologIds'],
                                                    $modelAR->general_lifespan_experiment_id,
                                                    $modelAR->gene_id
            );
        }
    }

    public function getTissuesIdsArray()
    {
        return LifespanExperimentToTissue::find()
            ->select('tissue_id')
            ->where(['lifespan_experiment_id' => $this->id])
            ->asArray()
            ->column();
    }

    public function setTissuesIdsArray(array $ids)
    {
        $this->tissuesIdsArray = $ids;
    }
    public function setOrthologIds($ids)
    {
        if (!$ids) {
            $ids = [];
        }
        $this->orthologIds = $ids;
    }

    public function getOrthologIds()
    {
        return LifespanExperimentToOrtholog::find()
            ->select('ortholog_id')
            ->where(['lifespan_experiment_id' => $this->id])
            ->asArray()
            ->column();
    }

    public function setModelOrganismId($id)
    {
        $this->modelOrganismId = $id;
    }

    public function getModelOrganismId()
    {
        return $this->getGeneralLifespanExperiment()
            ->select('model_organism_id')->distinct()->one()->model_organism_id;
    }

    private function saveTissues($tissuesIdsArray)
    {
        $currentTissuesIdsArray = $this->getTissuesIdsArray();

        if ($currentTissuesIdsArray !== $tissuesIdsArray) {
            if ($tissuesIdsArray) {
                $tissuesIdsArrayToDelete = array_diff($currentTissuesIdsArray, $tissuesIdsArray);
                $tissuesIdsToAdd = array_diff($tissuesIdsArray, $currentTissuesIdsArray);

                foreach ($tissuesIdsToAdd as $tissueIdToAdd) {
                    if (!is_numeric($tissueIdToAdd)) {
                        $tissueToAdd = Sample::createFromNameString($tissueIdToAdd);
                        $tissueIdToAdd = $tissueToAdd->id;
                    }
                    $lifespanExperimentToTissue = new LifespanExperimentToTissue();
                    $lifespanExperimentToTissue->lifespan_experiment_id = $this->id;
                    $lifespanExperimentToTissue->tissue_id = $tissueIdToAdd;
                    $lifespanExperimentToTissue->save();
                }
            } else {
                $tissuesIdsArrayToDelete = $currentTissuesIdsArray;
            }

            $arsToDelete = LifespanExperimentToTissue::find()->where(
                ['and', ['lifespan_experiment_id' => $this->id],
                    ['in', 'tissue_id', $tissuesIdsArrayToDelete]]
            )->all();
            foreach ($arsToDelete as $arToDelete) { // one by one for properly triggering "afterDelete" event
                $arToDelete->delete();
            }
        }
    }

    private function saveOrthologs($orthologIds, $typeRelations, $generalLe = false, $geneId = false)
    {
        $currentOrthologIds = $this->getOrthologIds();

        if ($currentOrthologIds !== $orthologIds) {
            if ($orthologIds) {
                $orthologIdsToDelete = array_diff($currentOrthologIds, $orthologIds);
                $orthologIdsToAdd = array_diff($orthologIds, $currentOrthologIds);

                foreach ($orthologIdsToAdd as $orthologIdToAdd) {
                    if (!is_numeric($orthologIdToAdd)) {
                        $orthologToAdd = Ortholog::createNewByName($orthologIdToAdd, $generalLe, $geneId);
                        $orthologIdToAdd = $orthologToAdd->id;
                    }
                    $lifespanExperimentToTissue = new LifespanExperimentToOrtholog();
                    $lifespanExperimentToTissue->lifespan_experiment_id = $this->id;
                    $lifespanExperimentToTissue->tissue_id = $orthologIdToAdd;
                    $lifespanExperimentToTissue->save();
                }
            } else {
                $orthologIdsToDelete = $currentOrthologIds;
            }

            $arsToDelete = LifespanExperimentToOrtholog::find()->where(
                ['and', ['lifespan_experiment_id' => $this->id],
                    ['in', 'ortholog_id', $orthologIdsToDelete]]
            )->all();
            foreach ($arsToDelete as $arToDelete) { // one by one for properly triggering "afterDelete" event
                $arToDelete->delete();
            }
        }
    }

    private function saveForeignEntity($typeRelations, $newIds, $generalLe = false, $geneId = false)
    {
        if($typeRelations == 1) {
            $relationKey = 'ortholog_id';
            $relationClass = LifespanExperimentToOrtholog::class;
            $currentIds = $this->getOrthologIds();
        }
        elseif($typeRelations == 2){
            $relationKey = 'tissue_id';
            $relationClass = LifespanExperimentToTissue::class;
            $currentIds = $this->getTissuesIdsArray();
        }

        if ($currentIds !== $newIds) {
            if ($newIds) {
                $IdsToDelete = array_diff($currentIds, $newIds);
                $idsToAdd = array_diff($newIds, $currentIds);

                foreach ($idsToAdd as $idToAdd) {
                    if (!is_numeric($idToAdd)) {
                        if ($typeRelations == 1) {
                            $entityToAdd = Ortholog::createNewByName($idToAdd, $generalLe, $geneId);
                        }
                        elseif($typeRelations == 2) {
                            $entityToAdd = Sample::createFromNameString($idToAdd);
                        }
                        $idToAdd = $entityToAdd->id;
                    }
                    $lifespanExperimentToEntity = new $relationClass;
                    $lifespanExperimentToEntity->lifespan_experiment_id = $this->id;
                    $lifespanExperimentToEntity->$relationKey = $idToAdd;
                    $lifespanExperimentToEntity->save();
                }
            } else {
                $IdsToDelete = $currentIds;
            }

            $arsToDelete = $relationClass::find()->where(
                ['and', ['lifespan_experiment_id' => $this->id],
                    ['in', $relationKey, $IdsToDelete]]
            )->all();
            foreach ($arsToDelete as $arToDelete) { // one by one for properly triggering "afterDelete" event
                $arToDelete->delete();
            }
        }
    }
}
